//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class HttpDownWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(HttpDown), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("StartDown", StartDown);
		L.RegFunction("ContinueDown", ContinueDown);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", Lua_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartDown(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			HttpDown obj = (HttpDown)ToLua.CheckObject(L, 1, typeof(HttpDown));
			string arg0 = ToLua.CheckString(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			obj.StartDown(arg0, arg1, arg2);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ContinueDown(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			HttpDown obj = (HttpDown)ToLua.CheckObject(L, 1, typeof(HttpDown));
			obj.ContinueDown();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}
}

